# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setting up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Creating setting.xml for Maven
      uses: whelk-io/maven-settings-xml-action@v21
      with:
        servers: |
          [{
              "id": "tibudget-repository-release",
              "username": "${{ secrets.AWS_GITHUB_KEY_ID }}",
              "password": "${{ secrets.AWS_GITHUB_KEY_VALUE }}"
          },{
              "id": "tibudget-repository-snapshot",
              "username": "${{ secrets.AWS_GITHUB_KEY_ID }}",
              "password": "${{ secrets.AWS_GITHUB_KEY_VALUE }}"
          }]
        repositories: |
          [{
            "id" : "tibudget-repository-release",
            "url" : "s3://tibudget-maven-repository/release",
            "releases": { "enabled": "true" }, 
            "snapshots": { "enabled": "false" }
          },{
            "id" : "tibudget-repository-snapshot",
            "url" : "s3://tibudget-maven-repository/snapshot",
            "releases": { "enabled": "false" }, 
            "snapshots": { "enabled": "true" }
          }]
    - name: Building with Maven
      run: mvn -B deploy --file pom.xml

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    # - name: Update dependency graph
    #   uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
